const assert = require('node:assert/strict');
const attach = require('./participant_bridge.cjs');
let count=0;let levels=[];let forwarded;
const tap = {read:()=>({installed:true,connections:count,levels})};
const voice = { createVoiceConnectionWithOptions:()=>{count++;return {destroy(){},setTransportOptions(value){forwarded=value;return 42;}};} };
attach(voice,tap);
const first=voice.createVoiceConnectionWithOptions('self',{context:'default'});
const options={audioDecoders:[{type:120,name:'opus',channels:1,params:{minptime:'10'}},{name:'other',channels:1}],audioEncoder:{channels:2}};
assert.equal(first.setTransportOptions(options),42);
assert.equal(forwarded.audioDecoders[0].channels,2);assert.equal(forwarded.audioDecoders[0].params.stereo,'1');
assert.equal(forwarded.audioDecoders[0].params.minptime,'10');assert.equal(options.audioDecoders[0].channels,1);
assert.equal(forwarded.audioEncoder,options.audioEncoder);assert.equal(forwarded.audioDecoders[1],options.audioDecoders[1]);
levels=[{connection:1,userId:'111',ageMs:0},{connection:2,userId:'222',ageMs:0}];
assert.deepEqual(voice.getParticipantStereoLevels().levels,[levels[0]]);
const stream=voice.createVoiceConnectionWithOptions('self',{context:'stream'});
assert.deepEqual(voice.getParticipantStereoLevels().levels,[levels[0]]);
const second=voice.createVoiceConnectionWithOptions('self',{context:'default'});
levels.push({connection:3,userId:'333',ageMs:0},{connection:3,userId:'444',ageMs:151});
assert.deepEqual(voice.getParticipantStereoLevels().levels,[levels[2]]);
second.destroy();assert.deepEqual(voice.getParticipantStereoLevels().levels,[levels[0]]);
first.destroy();stream.destroy();assert.deepEqual(voice.getParticipantStereoLevels().levels,[]);
assert.throws(()=>attach({}, {read:()=>({installed:false,error:'Unaudited native voice binary'})}),/Unaudited/);
console.log('PASS receiver stereo parameters, preserved encoder/options/return, connection identity, stream isolation, reconnect, expiry, destroy, fail closed');
